### ISSUE TITLE
beagleG runs on debian 8.3 problem, These is problem to Enable the STEP

### ISSUE THREAD

**Issue by Dark-Guan** [hzeller/beagleg#14]
Now, I test beagleG on debian 8.3.

I solve the problem of pruss,but now the step can't be enable .

The debian version is one-debian-8.3-lxqt-4gb-armhf-2016-01-24-4gb.img

**Comment by hzeller** [comment]
If you have a `-ti` kernel, they won't work as they play with some experimental future way to interact with the PRU. make sure to install a `-bone` kernel.
I have a 4.4.14-bone on my set-up.

**Comment by hzeller** [comment]
Did you get it to work ? (meaning: can we close this ?)

**Comment by Dark-Guan** [comment]
Yes,it works out.
I should use "M62 P15" and "M80" to enable CRAMPS to work,it's fine.
I figure out this is caused by the step of aux pin initial. I will try to solve them.
