### ISSUE TITLE
[feature] Arc speed profile with jerk control

### ISSUE THREAD

**Issue by lromor** [hzeller/beagleg#8]
Hello Everyone, 
do you have any thoughts about how to add jerk in the speed profile in order to smooth-out the accelerations and avoid machine trashing (for example for the arcs)?

**Comment by bigguiness** [comment]
The latest update to the planner seems to cover this issue. It's not actually accounting for jerk but the accelerations are now smooth. Can this issue be closed?

**Comment by hzeller** [comment]
Yeah, let's close this for now: the main part - arcs smoothing - is working now thanks to great work by Hartley. The jerk planning is a thing on the development TODO list.

**Comment by bigguiness** [comment]
Henner, this still needs to be closed. ;-)
